language: php

php: 7.2

addons:
 apt:
  packages:
  - lftp
  - fontforge

before_install:
- composer global require hirak/prestissimo

install:
- composer install
- nvm install 10
- npm install --global grunt-cli
- npm install
- cd vendor/redaxmedia/ncss-template && npm install && cd -
- cd vendor/redaxscript/redaxscript && npm install && cd -

script:
- replace 'vendor/redaxscript' '../../redaxscript' -- vendor/redaxmedia/ncss-template/templates/ncss/assets/styles/_ncss.css
- grunt build --gruntfile vendor/redaxmedia/ncss-template/gruntfile.js
- grunt build --gruntfile vendor/redaxscript/redaxscript/gruntfile.js
- grunt
- grunt config
- grunt lock

after_success:
- grunt deploy

notifications:
 email:
 - info@redaxmedia.com
