name: ci

on: [ push, pull_request ]

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up PHP 7.4
    uses: shivammathur/setup-php@2.7.0
    with:
     php-version: 7.4
  - name: Set up Node 15
    uses: actions/setup-node@v1
    with:
     node-version: 15
  - run: sudo apt install lftp
  - run: composer install 
  - run: npm install
  - run: npm install --prefix=vendor/redaxmedia/ncss-template
  - run: npm install --prefix=vendor/redaxscript/redaxscript
  - run: replace 'vendor/redaxscript' '../../redaxscript' -- vendor/redaxmedia/ncss-template/templates/ncss/assets/styles/_ncss.css
  - run: grunt build --gruntfile vendor/redaxmedia/ncss-template/gruntfile.js
  - run: grunt build --gruntfile vendor/redaxscript/redaxscript/gruntfile.js
  - run: node_modules/.bin/grunt copy
  - run: node_modules/.bin/grunt config
  - run: node_modules/.bin/grunt lock
  - run: node_modules/.bin/grunt deploy
    env:
     FTP_URL: ${{ secrets.FTP_URL }}
