name: ci

on: [ push, pull_request ]

jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up Node 15
    uses: actions/setup-node@v1
    with:
     node-version: 15
  - run: npm install --legacy-peer-deps
  - run: node_modules/.bin/grunt copy
  - run: node_modules/.bin/grunt config
  - run: node_modules/.bin/grunt lock
  - run: node_modules/.bin/grunt deploy
